--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: article; Type: TABLE; Schema: public; Owner: noumbis
--

CREATE TABLE public.article (
    id bigint NOT NULL,
    contenu text,
    date_publication date,
    titre character varying(255)
);


ALTER TABLE public.article OWNER TO noumbis;

--
-- Name: article_id_seq; Type: SEQUENCE; Schema: public; Owner: noumbis
--

ALTER TABLE public.article ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.article_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: commentaire; Type: TABLE; Schema: public; Owner: noumbis
--

CREATE TABLE public.commentaire (
    id bigint NOT NULL,
    contenu character varying(255),
    date_commentaire date,
    article_id bigint
);


ALTER TABLE public.commentaire OWNER TO noumbis;

--
-- Name: commentaire_id_seq; Type: SEQUENCE; Schema: public; Owner: noumbis
--

ALTER TABLE public.commentaire ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.commentaire_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: article article_pkey; Type: CONSTRAINT; Schema: public; Owner: noumbis
--

ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);


--
-- Name: commentaire commentaire_pkey; Type: CONSTRAINT; Schema: public; Owner: noumbis
--

ALTER TABLE ONLY public.commentaire
    ADD CONSTRAINT commentaire_pkey PRIMARY KEY (id);


--
-- Name: commentaire fkpl8x2ccino75hr790mhtghbt9; Type: FK CONSTRAINT; Schema: public; Owner: noumbis
--

ALTER TABLE ONLY public.commentaire
    ADD CONSTRAINT fkpl8x2ccino75hr790mhtghbt9 FOREIGN KEY (article_id) REFERENCES public.article(id);


--
-- PostgreSQL database dump complete
--

